-- Fictional profile data for Assignment 2.
create table public.profiles (
  id bigint generated by default as identity primary key,
  username text not null unique,
  full_name text not null,
  role text not null check (role in ('student', 'instructor', 'admin')),
  city text,
  bio text,
  interests text[] not null default '{}',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.profiles
  (username, full_name, role, city, bio, interests, is_active)
values
  ('maya_chen', 'Maya Chen', 'student', 'New York',
   'Learning how to build useful AI-powered products.',
   array['Generative AI', 'Design', 'Photography'], true),
  ('liam_brooks', 'Liam Brooks', 'student', 'Boston',
   'Interested in data visualization and responsible technology.',
   array['Data Visualization', 'Web Development', 'Music'], true),
  ('sofia_martinez', 'Sofia Martinez', 'instructor', 'Chicago',
   'Teaching product design and human-centered computing.',
   array['Education', 'UX Research', 'Accessibility'], true),
  ('noah_kim', 'Noah Kim', 'student', 'Seattle',
   'Experimenting with full-stack applications and cloud platforms.',
   array['Next.js', 'Databases', 'Cloud'], false);

alter table public.profiles enable row level security;

revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to anon;

create policy "Allow anonymous read access"
on public.profiles
for select
to anon
using (true);
